#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Test Linux Build and Test Workflow

on:
  workflow_dispatch:

jobs:
  test-linux:
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@937e1789749e691f4c10719078efb65f7648c5a3
    with:
      enable_linux_checks: true
      enable_windows_checks: false
